---
# This is an ansible play to setup the requirement on the node for clearML
# Configure your inventory to point to the right host
- hosts: all
  gather_facts: no
  become: yes
  vars:
    docker_config_file: /etc/docker/daemon.json
    clearml_docker_config:
      default-ulimits:
        nofile:
          name: "nofile"
          hard: 65536
          soft: 1024
        memlock:
          name: "memlock"
          soft: -1
          hard: -1

  tasks:
    - name: Load docker json file
      ansible.builtin.slurp:
        src: "{{ docker_config_file }}"
      register: docker_daemon_conf
    - name: Override docker daemon config
      copy:
        content: "{{ docker_daemon_conf.content | b64decode | from_json | combine(clearml_docker_config) | to_nice_json }}"
        dest: "{{ docker_config_file }}"
      notify:
        - Docker restart
    - name: Configure sysctl
      sysctl:
        name: vm.max_map_count
        value: 262144
        sysctl_set: yes
      notify:
        - Docker restart

  handlers:
    - name: Docker restart
      ansible.builtin.service:
        name: docker
        state: restarted
