apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: clearml-server
    app.kubernetes.io/part-of: clearml-server
  name: mongo-service
  namespace: clearml
spec:
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: clearml-server
    app.kubernetes.io/part-of: clearml-server
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: clearml-server
    app.kubernetes.io/part-of: clearml-server
  name: mongo
  namespace: clearml
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/instance: clearml-server
      app.kubernetes.io/part-of: clearml-server
  minReadySeconds: 20
  progressDeadlineSeconds: 30
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/instance: clearml-server
        app.kubernetes.io/part-of: clearml-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - clearml
      containers:
      - image: mongo:3.6.5
        name: mongo
        args: ["--setParameter", "internalQueryExecMaxBlockingSortBytes=196100200"]
        resources:
          requests:
            memory: "125M"
            cpu: "200m"
          limits:
            memory: "250M"
            cpu: "300m"
        volumeMounts:
        - mountPath: /data/db
          name: mongo-hostpath0
        - mountPath: /data/configdb
          name: mongo-hostpath1
      restartPolicy: Always
      nodeSelector:
        app: clearml
      volumes:
      - name: mongo-hostpath0
        hostPath:
          path: /opt/clearml/data/mongo/db
      - name: mongo-hostpath1
        hostPath:
          path: /opt/clearml/data/mongo/configdb