apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: agentservices
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: clearml-server
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: agentservices
  namespace: {{ .Values.clearml.namespace }}
spec:
  selector:
    matchLabels:
          app.kubernetes.io/name: agentservices
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/part-of: clearml-server
          app.kubernetes.io/managed-by: {{ .Release.Service }}
  minReadySeconds: 20
  progressDeadlineSeconds: 30
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
          app.kubernetes.io/name: agentservices
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/part-of: clearml-server
          app.kubernetes.io/managed-by: {{ .Release.Service }}
          helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
                - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - clearml
      containers:
      - image: allegroai/clearml-agent-services:latest
        name: agentservices
        securityContext:
          privileged: true
        volumeMounts:
          - name: dockersock
            mountPath: "/var/run/docker.sock"
          - name: agent-data
            mountPath: /root/.clearml
        env:
          - name: CLEARML_HOST_IP
            value: {{ .Values.agentservices.clearmlHostIp }}
          - name: CLEARML_API_HOST
            value: {{ .Values.agentservices.clearmlApiHost }}
          - name: CLEARML_WEB_HOST
            value: {{ .Values.agentservices.clearmlWebHost }}
          - name: CLEARML_FILES_HOST
            value: {{ .Values.agentservices.clearmlFilesHost }}
          - name: CLEARML_AGENT_GIT_USER
            value: {{ .Values.agentservices.clearmlGitUser }}
          - name: CLEARML_AGENT_GIT_PASS
            value: {{ .Values.agentservices.clearmlGitPassword }}
          - name: CLEARML_API_ACCESS_KEY
            value: {{ .Values.agentservices.clearmlAccessKey }}
          - name: CLEARML_API_SECRET_KEY
            value: {{ .Values.agentservices.clearmlSecretKey }}
          - name: CLEARML_AGENT_UPDATE_VERSION
            value: {{ .Values.agentservices.agentVersion }}
          - name: CLEARML_AGENT_DEFAULT_BASE_DOCKER
            value: {{ .Values.agentservices.defaultBaseDocker }}
          - name: AWS_ACCESS_KEY_ID
            value: {{ .Values.agentservices.awsAccessKeyId }}
          - name: AWS_SECRET_ACCESS_KEY
            value: {{ .Values.agentservices.awsSecretAccessKey }}
          - name: AWS_DEFAULT_REGION
            value: {{ .Values.agentservices.awsDefaultRegion }}
          - name: AZURE_STORAGE_ACCOUNT
            value: {{ .Values.agentservices.azureStorageAccount }}
          - name: AZURE_STORAGE_KEY
            value: {{ .Values.agentservices.azureStorageKey }}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: {{ .Values.agentservices.googleCredentials }}
          - name: CLEARML_WORKER_ID
            value: {{ .Values.agentservices.clearmlWorkerId }}
          - name: CLEARML_AGENT_DOCKER_HOST_MOUNT
            value: {{ .Values.agentservices.clearmlDockerHostMount }}
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: agent-data
        hostPath:
          path: /opt/clearml/agent
      restartPolicy: Always
      nodeSelector:
        {{ .Values.clearml.nodeSelector }}
