---
- name: Build inventory from kubernetes nodes
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Get Kubernetes nodes
      set_fact:
        nodes: "{{ lookup('k8s', api_version='v1', kind='node') }}"
    - name: Add host to inventory
      add_host:
        hostname: "{{ item[1].address }}"
        ansible_ssh_host: "{{ item[0].address }}"
        groups:
        - Nodes
      with_list: "{{ nodes | json_query('[*].status.addresses') }}"
